apiVersion: v1
kind: Service
metadata:
  name: frontend-app
  labels:
    app: guestbook
    tier: frontend
spec:
  # generiranje vanjeke IP preko melatLB (type: LoadBalancer)
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: guestbook
    tier: frontend
